// import { IProduct } from "./types";

// export const Products: IProduct[] = [
//     {
//         id: "1",
//         name: "Laptop Pro 15",
//         price: 1999.99,
//         imageUrl: "/images/laptop-pro-15.jpg",
//         description: "A high-performance laptop for professionals.",
//         inStock: true,
//         category: "laptops",
//         rating: 4.5,
//         count: 10,
//         createdAt: "2023-08-01T10:00:00.000Z",
//         updatedAt: "2023-08-01T10:00:00.000Z",
//     },
//     {
//         id: "2",
//         name: "Wireless Earbuds X",
//         price: 149.99,
//         imageUrl: "/images/wireless-earbuds-x.jpg",
//         description: "Wireless earbuds with great sound quality.",
//         inStock: true,
//         category: "headphones",
//         rating: 4.2,
//         count: 5,
//         createdAt: "2023-08-01T10:00:00.000Z",
//         updatedAt: "2023-08-01T10:00:00.000Z",
//     },
//     {
//         id: "3",
//         name: "Smartphone Z",
//         price: 799.99,
//         imageUrl: "/images/smartphone-z.jpg",
//         description: "A powerful smartphone with advanced features.",
//         inStock: true,
//         category: "smartphones",
//         rating: 4.8,
//         count: 8,
//         createdAt: "2023-08-01T10:00:00.000Z",
//         updatedAt: "2023-08-01T10:00:00.000Z",
//     },
//     {
//         id: "4",
//         name: "4K Ultra HD TV",
//         price: 1199.99,
//         imageUrl: "/images/4k-ultra-hd-tv.jpg",
//         description: "A stunning 4K TV with advanced features.",
//         inStock: true,
//         category: "tvs",
//         rating: 4.6,
//         count: 6,
//         createdAt: "2023-08-01T10:00:00.000Z",
//         updatedAt: "2023-08-01T10:00:00.000Z",
//     },
//     {
//         id: "5",
//         name: "Smartwatch Y",
//         price: 299.99,
//         imageUrl: "/images/smartwatch-y.jpg",
//         description: "A stylish smartwatch with health tracking features.",
//         inStock: true,
//         category: "watches",
//         rating: 4.3,
//         count: 12,
//         createdAt: "2023-08-01T10:00:00.000Z",
//         updatedAt: "2023-08-01T10:00:00.000Z",
//     },
//     {
//         id: "6",
//         name: "Gaming Laptop G",
//         price: 2499.99,
//         imageUrl: "/images/gaming-laptop-g.jpg",
//         description: "A high-end gaming laptop with powerful graphics.",
//         inStock: false,
//         category: "laptops",
//         rating: 4.7,
//         count: 0,
//         createdAt: "2023-08-01T10:00:00.000Z",
//         updatedAt: "2023-08-01T10:00:00.000Z",
//     },
// ];
